[program:ai-dev-horizon]
process_name=%(program_name)s
command=php /var/www/html/projetos/ai-dev/ai-dev-core/artisan horizon
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/projetos/ai-dev/ai-dev-core/storage/logs/horizon.log
stopwaitsecs=3600

[program:ai-dev-gemini-proxy]
process_name=%(program_name)s
command=python3 /var/www/html/projetos/ai-dev/infrastructure/proxy/gemini_proxy.py
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/projetos/ai-dev/infrastructure/proxy/gemini_proxy_py.log
stopwaitsecs=10

[program:ai-dev-claude-proxy]
process_name=%(program_name)s
command=python3 /var/www/html/projetos/ai-dev/infrastructure/proxy/claude_proxy.py
autostart=true
autorestart=true
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/projetos/ai-dev/infrastructure/proxy/claude_debug.log
stopwaitsecs=10
